<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="br.com.gcs.test.CL_MeusDadosTest" tests="4" time="31.220" ignored="1" failures="1" timestamp="26 fev 2017 20:33:06 GMT" skipped="0" hostname="DESKTOP-S0R30VE" errors="0">
  <testcase name="dataInvalida" time="3.222" classname="br.com.gcs.test.CL_MeusDadosTest">
    <failure type="org.junit.ComparisonFailure" message="expected:&lt;Data Incorreta[X]&gt; but was:&lt;Data Incorreta[]&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<Data Incorreta[X]> but was:<Data Incorreta[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at br.com.gcs.test.CL_MeusDadosTest.dataInvalida(CL_MeusDadosTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at br.com.gcs.test.Suite.main(Suite.java:19)
]]>
    </failure>
  </testcase> <!-- dataInvalida -->
  <testcase name="nomeIncompleto" time="4.280" classname="br.com.gcs.test.CL_MeusDadosTest"/>
  <testcase name="cpfInvalido" time="18.104" classname="br.com.gcs.test.CL_MeusDadosTest"/>
  <testcase name="validarRenda" time="5.614" classname="br.com.gcs.test.CL_MeusDadosTest"/>
  <testcase name="avancar" classname="br.com.gcs.test.CL_MeusDadosTest">
    <skipped/>
  </testcase> <!-- avancar -->
</testsuite> <!-- br.com.gcs.test.CL_MeusDadosTest -->
